version: '3'

services:
    gameplatform:
        environment:
            DATABASE_URL: ${DATABASE_URL}
            NODE_ENV: production
            PORT: 3000
        depends_on:
            - postgres
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: 'tyson007/gameplatform:latest'
        ports:
            - '3000:3000'
    postgres:
        image: 'postgres:13'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        restart: always
        volumes:
            - ./pgdata:/var/lib/postgresql/data
